apiVersion: v1
kind: Service
metadata:
  namespace: sonarqube
  name: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9000
